### ISSUE TITLE
No all user field data saved upon returning from PayFast after checkout.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-payfast#85] opened 2022-10-12 09:34 UTC
When a user checks out for a level with multiple user fields created with code not all user field data is saved upon returning from PayFast after a successful checkout.

**To Reproduce**

1. Create multiple user fields with code consisting of various text, textarea, and grouped checkboxes and add the code to a customization plugin.
2. Set Payment Gateway to PayFast
3. Check out for level
4. Verify which field's data was saved in either the user profile or the `wp_usermeta` table.

**Additional Notes**

During testing the first two required text field types, e.g. first_name, and last_name, and grouped-checkbox field types were successfully captured and saved but the remaining text and textarea field types were not saved.

**Moderators Only**: #452405

**Comment by ipokkel** [comment] 2022-10-14 04:22
A user reported that after uninstalling the customization plugin with the code for custom fields and adding the code to a third-party code plugin their custom user fields were captured successfully after checkout.

While testing this in a live testing environment it could not be replicated and the issue of only some fields being captured persisted.

**Comment by Bridget411** [comment] 2022-11-10 10:49
I am the user referred to above.  The problem is not fixed.  The additional fields do not display if a payment is required, eg PayFast, as referred to in the original post.
I am really needing a fix for this but don't have the knowledge to do it myself.
Hoping someone out there can help please.

**Comment by andrewlimaza** [comment] 2022-11-10 14:15
We are looking into this issue @Bridget411, unfortunately I don't have a timeframe when this will be released or available.

Thank you for your patience.

**Comment by andrewlimaza** [comment] 2022-11-30 13:19
@Bridget411 we have just created a Pull Request for this and still testing it before being merged. I know this is important to you, you may test this out on your site by applying this code change to your site -> https://github.com/strangerstudios/pmpro-payfast/pull/87

**Closed** 2022-11-30 14:14 UTC
Labels: Blocking Next Release

**Comment by Bridget411** [comment] 2022-11-30 14:53
Hello

THANK YOU so much for this information and the fix you’ve created.  

I have added the code (on the green background) to the end of the pmpro-payfast.php file.  Hoping that’s all I need to do.  Would it be better to add it as a code snippet?  If so do I create a snippet and just paste that new code in?

Sorry for asking but my knowledge in this area is very limited.

**Comment by andrewlimaza** [comment] 2022-11-30 14:57
Please open a support ticket on https://www.paidmembershipspro.com/support and someone from our team would be able to assist you to implement this code onto your site.

A release should be available in the next couple of days.

**Comment by andrewlimaza** [comment] 2022-12-01 10:07
@Bridget411, we have just released v1.4 of PayFast and this is included in the fix. Please update your plugin to the latest version and let us know if you run into any issues.

Thank you once again for your patience.

**Comment by Bridget411** [comment] 2022-12-01 10:11
Hi Andrew

THANKS AGAIN. I will do so and let you know how it goes.

Much appreciated.
